# Generated by Django 2.0.4 on 2018-04-11 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arg_name', models.CharField(max_length=80)),
                ('arg_type', models.CharField(choices=[('int', 'int'), ('float', 'float'), ('string', 'string'), ('infile', 'infile'), ('outfile', 'outfile')], default='string', max_length=20)),
                ('arg_default', models.CharField(default=None, max_length=100)),
                ('arg_format', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WebAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='arg',
            name='api_func',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sangerdev.WebAPI'),
        ),
    ]
