# Generated by Django 2.0.4 on 2018-04-11 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sangerdev', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arg',
            old_name='api_func',
            new_name='api_name',
        ),
    ]
