# Generated by Django 2.0.4 on 2018-04-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sangerdev', '0004_auto_20180413_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arg',
            name='arg_default',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='arg',
            name='arg_format',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
