# Generated by Django 2.0.4 on 2018-04-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sangerdev', '0005_auto_20180414_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arg',
            name='arg_default',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='arg',
            name='arg_format',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
