# Generated by Django 2.0.4 on 2018-04-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sangerdev', '0006_auto_20180415_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webapi',
            name='description',
        ),
        migrations.AlterField(
            model_name='arg',
            name='arg_default',
            field=models.CharField(default='None', help_text='Default Value', max_length=100),
        ),
        migrations.AlterField(
            model_name='arg',
            name='arg_format',
            field=models.CharField(default='None', help_text='Format Example: ref_rna.exp_matrix', max_length=100),
        ),
        migrations.AlterField(
            model_name='arg',
            name='arg_name',
            field=models.CharField(help_text='Argument Name', max_length=80),
        ),
        migrations.AlterField(
            model_name='arg',
            name='arg_type',
            field=models.CharField(choices=[('int', 'int'), ('float', 'float'), ('string', 'string'), ('infile', 'infile'), ('outfile', 'outfile')], default='string', help_text='Argument Type', max_length=20),
        ),
        migrations.AlterField(
            model_name='webapi',
            name='api_name',
            field=models.CharField(help_text='Example: ref_rna.exp_venn', max_length=100),
        ),
        migrations.AlterField(
            model_name='webapi',
            name='controller',
            field=models.CharField(help_text='Example: ref_rna_controller', max_length=100),
        ),
        migrations.AlterField(
            model_name='webapi',
            name='package_rel_path',
            field=models.CharField(help_text='Example: ref_rna.exp_venn_package', max_length=200),
        ),
    ]
